server:
  port: 3399
spring:
  profiles:
    active: dev
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false #是否将自己注册到eureka中
    fetch-registry: false #是否从eureka中获取信息
    service-url:
      #defaultZone: http://localhost:3399
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/